kind: pipeline
type: docker
name: qrc

steps:
- name: test
  image: golang:1.14
  commands:
  - go test -mod=readonly .

---

kind: pipeline
type: docker
name: cmd/qrc2zip

steps:
- name: build
  image: golang:1.14
  commands:
  - go build -mod=readonly ./cmd/qrc2zip
- name: run
  image: golang:1.14
  commands:
  - ./qrc2zip --help

depends_on:
- qrc

---

kind: pipeline
type: docker
name: test/nickel.15505

steps:
- name: build
  image: golang:1.14
  command: ['./test/nickel.15505.sh', '0']
- name: download
  image: golang:1.14
  commands:
  - apt-get update -qqy && apt-get install -qqy xz-utils
  - ./test/nickel.15505.sh 1
- name: extract
  image: golang:1.14
  command: ['./test/nickel.15505.sh', '2']
- name: sha1sums
  image: golang:1.14
  command: ['./test/nickel.15505.sh', '3']
- name: list
  image: golang:1.14
  command: ['./test/nickel.15505.sh', '4']
- name: cleanup
  image: golang:1.14
  command: ['./test/nickel.15505.sh', '5']

depends_on:
- qrc
- cmd/qrc2zip
